Epicdeals/Epicdeals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("seller/", include ("seller.urls")),
    path("", include("deals.urls")),
   
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Epicdeals/deals/urls.py
from django.urls import path
from .views import *


app_name = "deals"
urlpatterns = [
    
     path("" , HomeView.as_view() , name="home"),
     path("about/", AboutView.as_view(), name="about"),
     path("all_products/", All_ProductsView.as_view(), name="all_product"),
     path("product/<str:slug>/" ,ProductDetailView.as_view(),name = "productdetail"),
     path("add-to-cart-<int:pro_id>/" , AddtoCartView.as_view(), name="addtocart"),
     path("my-cart/", MyCartView.as_view(), name="mycart"),
     path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
     path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
     path("checkout/", CheckoutView.as_view(), name="checkout"),
     path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
     path("logout/",CustomerLogoutView.as_view(), name="customerlogout"),
     path("login/",CustomerLoginView.as_view(), name="customerlogin"),
     path("profile/",CustomerprofileView.as_view(), name="customerprofile"),
     path("profile/order-<int:pk>/",CustomerOrderDetailView.as_view(), name="customerorderdetail"),



     path("<str:name>/" , Category_view.as_view(), name = "category"),
    

]

Epicdeals/seller/urls.py
from django.urls import path
from .views import *
from . import views



app_name = "seller"
urlpatterns = [
     path("", views.SellerLogin, name="sellerlogin"),
     path("sellerregistration/",views.sellerregistration, name="sellerregistration"),
     path("sellerlogout/",SellerLogoutView.as_view(),name="sellerlogout"),
     path("selleraddproduct/<str:usr>/",SellerAddproduct.as_view(), name = "selleraddproduct"),
     path("sellerhome/<str:selleruser>/", SellerHome.as_view(),name="sellerhome"),
     path("<str:st>-<int:pk>/",SellerOrderDetailView.as_view(), name="sellerorderdetail"),
     path("<str:store_name>/",SellerProfile.as_view(), name="sellerprofile"),
     
     
]

Epicdeals/deals/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
   user = models.OneToOneField(User,on_delete = models.CASCADE )
   full_name = models.CharField(max_length = 200)
   address = models.CharField(max_length = 200,null = True, blank = True)
   joined_on = models.DateTimeField(auto_now_add = True)

   def __str__(self):
       return self.full_name



class Category(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField(unique = True)

    def __str__ (self):
        return self.title


class Seller_store(models.Model):
    seller_user = models.OneToOneField(User,on_delete = models.CASCADE,null=True)
    password = models.CharField(max_length=50,null=True)
    store_name = models.CharField(max_length=200)
    bank_account = models.IntegerField()
    address = models.CharField(max_length=200)
    contact_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
       return self.store_name


class Product(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField(unique = True)
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    image = models.ImageField(upload_to ="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length = 100,null = True , blank = True)
    return_policy = models.CharField(max_length = 100,null = True , blank = True)
    seller_store = models.ForeignKey(Seller_store, on_delete=models.CASCADE)


    def __str__(self):
        return self.title




class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.SET_NULL, null = True,blank=True)
    total = models.PositiveIntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)


    def __str__(self):
        return "Cart: "+ str(self.id)




class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.ForeignKey(Product , on_delete = models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()


    def __str__(self):
        return "Cart: "+ str(self.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (

    ("Order Received" , "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Ordeer Canceled", "Order canceled"),
)

PAYMENT_STATUS = (
    ("Payment Pending" , "Payment Pending"),
    ("Payment Done", "Payment Done"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete = models.CASCADE)
    ordered_by = models.CharField(max_length = 200)
    shipping_address = models.CharField(max_length = 200)
    moblile = models.CharField(max_length = 15)
    email = models.EmailField(null = True , blank = True)
   
    subtotal = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length = 50,choices = ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add = True)
    payment_status = models.CharField(max_length=200,choices=PAYMENT_STATUS,default='Payment Pending',blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

Epicdeals/templates/about.html
{% extends 'base.html' %}

{%block title%} 
about
{%endblock%}


{%block body%}
<h1>successfully checkout</h1>
{%endblock%}

Epicdeals/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
        {%endblock%}

    </title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



</head>
<body id="body">
  

    <nav style="display: flex; justify-content: space-between; align-items: center; background-color: #1f2a33;
    padding: 10px; color: #fff; font-family: Arial, sans-serif; font-size: 25px;">
       <ul style="display: flex;">
           <li style="list-style: none; margin-right: 15px;"><a href = "/">Home</a></li>
           <li style="list-style: none; margin-right: 15px;"><a href = "/about">About</a></li>
           {%comment%}
           <li style="list-style: none; margin-right: 15px;"><a href = "/all_products">Categories</a></li>
           {%endcomment%}
           <li style="list-style: none; margin-right: 15px;">
            


            <div style="position: relative;">
                <span style="cursor: pointer;" id="category" >Category</span>
                <div id="dropdownOptions" style="display: none; position: absolute; top: 100%; left: 0; background-color: #f9f9f9; border: 1px solid #ccc; 
                padding: 8px;">
                 {%for cat in category%}
                  <a href="/{{cat.slug}}" style="display:block; padding: 4px; text-decoration: none; color: #333;"><p style="font-size: 18px;">{{cat.slug}}</p></a> 
                 {%endfor%}

                 <a href="/all_products" style="display:block; padding: 4px; text-decoration: none; color: #333;"><p style="font-size: 18px;">All Product</p></a> 
                 
                </div>
              </div>
              
              

            
              
            
           </li>
           
       </ul>
       <ul style="display: flex;">
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'deals:mycart' %}">View Cart</a></li>
           {% if request.user.customer %}
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'deals:customerprofile' %}">{{request.user.username}}</a></li> 
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'deals:customerlogout' %}">Logout</a></li>
           {% else %}
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'deals:customerregistration' %}">Register</a></li> 
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'deals:customerlogin' %}">Login</a></li> 
           {% endif %}
           
       </ul>
   </nav>
          

   <script>
     

     
  var category = document.getElementById("category");
  var dropdownOptions = document.getElementById("dropdownOptions");
  category.addEventListener("click", function(event) {


    if (dropdownOptions.style.display === "none") {
      dropdownOptions.style.display = "block";
    } else {
      dropdownOptions.style.display = "none";
    }



  });

  
   
  </script>
    

       {% block body %}
       {%endblock%}
</body>
</html>

Epicdeals/templates/catagory.html
{% extends 'base.html' %}

{%block title%} 
name
{%endblock%}


{%block body%}


<div class="container" style="margin-top: 40px;">

    <h1 class="text-center">Welcome To Our Ecommerce Website</h1>
    <div class="row mt-3">

     {% for p in product_list %}
     <div style="border: 1px solid #ccc; padding: 10px; text-align: center;background-color: rgb(229, 240, 240);height:400px;width:300px;margin: 20px;">
       <a href="/product/{{p.slug}}"><img src="{{p.image.url}}" alt="Product Image" style="width: 100%;height: 250px;">
       <h3 style="margin-top: 10px;">{{p.title}}</h3></a>
       <p style="font-size: 18px;">TK.<strike> {{p.marked_price}}</strike> {{p.selling_price}}</p>
       <a href="{% url 'deals:addtocart' p.id%}"><button style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; font-size: 16px;">Add to Cart</button></a>
      </div>
   
      {% endfor %}

     </div>

 
  


 
</div>

  


{%endblock%}

Epicdeals/templates/customerorderdetail.html
{% extends 'base.html' %}

{% block title %} Order Detail{% endblock %}
{% block body %}

 <div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-md mx-auto">
           <h3>Order Details</h3><hr>
           <p><span class="font-weight-bold">Order ID: </span>#ORDER_{{ord_obj.id}}</p>
           <p><span class="font-weight-bold">Order Status: </span>{{ord_obj.order_status}}</p>
           <p><span class="font-weight-bold">Order On: </span>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
           <p><span class="font-weight-bold">Customer Information: </span>By {{ord_obj.ordered_by}}, ({{ord_obj.moblile}})</p>
           <p><span class="font-weight-bold">Shipping Address: </span>{{ord_obj.shipping_address}}</p>
           <p><span class="font-weight-bold">Email:  </span>{{ord_obj.email}}</p>

           <h3>Ordered Items</h3>
           <table class="table">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Item</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for cp in ord_obj.cart.cartproduct_set.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a target="_blank" href="{%url 'deals:productdetail' cp.product.slug%}">{{ cp.product.title }}({{cp.product.id}})</a></td>
                    <td>{{cp.rate}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.subtotal}}</td>

                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total: </th>
                    <th>Rs.{{ord_obj.total}}/-</th>
                </tr>
            </tbody>
           </table>
        </div>
        
    </div>
 </div>

{%endblock%}

Epicdeals/templates/customerprofile.html
{% extends 'base.html' %}

{% block title %} My Profile {% endblock %}
{% block body %}

<div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-md-4">

            <h3>Details Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span>{{customer.full_name}}</p>
            <p><span class="font-weight-bold">username: </span>{{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span>{{customer.user.email}}</p>
            <p><span class="font-weight-bold">Adress: </span>{{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span>{{customer.joined_on}}</p>
            
        </div>
        <div class = "col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order_id</th>
                        <th>Amount</th>
                        <th>Ordered_on</th>
                        <th>Status</th>
                        
                    </tr>
                    <tbody>
                        
                        {% for ord in orders %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'deals:customerorderdetail' ord.id %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </thead>
            </table>


        </div>
    </div>
</div>


{% endblock %}

Epicdeals/templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}
{% block body %}
<div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Register</button>
            </form>
            <p>Alreay have an account?<a href="{% url 'deals:customerlogin' %}">Login</a></p>
        </div>
    </div>
</div>
{% endblock %}

Epicdeals/templates/home.html
{% extends 'base.html' %}

{%block title%} 
Home
{%endblock%}


{%block body%}
<div class="container"style="margin-top:40px">

     <h1 class="text-center">Welcome To Our Ecommerce Website</h1>
     <div class="row mt-3">

      {% for p in product_list %}
      <div style="border: 1px solid #ccc; padding: 10px; text-align: center;background-color: rgb(229, 240, 240);height:400px;width:300px;margin: 20px;">
        <a href="/product/{{p.slug}}/"><img src="{{p.image.url}}" alt="Product Image" style="width: 100%;height: 250px;">
        <h3 style="margin-top: 10px;">{{p.title}}</h3></a>
        <p style="font-size: 18px;">TK.<strike> {{p.marked_price}}</strike> {{p.selling_price}}</p>
        <a href="{% url 'deals:addtocart' p.id%}"> <button style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; font-size: 16px;">Add to Cart</button></a>
       </div>
    
       {% endfor %}

      </div>

  
   


  
</div>
  


{%endblock%}

Epicdeals/templates/productdetail.html
{%extends 'base.html'%}
{% block title%} {{ product.title }}{%endblock%}


{%block body %}
  
  <div class="container">
    <h3>Product: {{product.title}}</h3><hr>

    <div class="row">

      <div class="col-md-6">
        <img src="{{product.image.url}}" alt="" class="img-fluid"style="height:450px">
      </div>

      <div class="col-md-6">
        <h4>{{product.title}}</h4>
        <h5>Category: {{product.category}}</h5>
        <h5>Price: <strike>Rs. {{product.marked_price}}</strike>  Rs. {{product.selling_price}}</h5>
        <a href="{% url 'deals:addtocart' product.id%}" class="btn btn-info">Add To Cart</a>
        <hr>
        <p class="text-info">Warranty: {{product.warranty}}</p>
        <p class="text-info">Return Policy: {{product.return_policy}}</p>
        <hr>
        <p>{{product.description}}</p>
      </div>

    </div>


  </div>


{%endblock%}

Epicdeals/templates/selleraddproduct.html
{% extends 'sellerbase.html' %}

{% block title %} Seller Add Product{% endblock %}
{% block body %}

<div style="display: flex; justify-content: center;margin:40px;height: 40px;">
<h2>Add Your Product</h2>
</div>
<div class="container" style="display: flex; justify-content: center;margin-bottom:100px;">
    
<form action="{% url 'seller:selleraddproduct' st %}" method="POST" enctype="multipart/form-data" style="width: 50%;">
    {% csrf_token %}
    
    <div class="seller-add-product-form">
      <label for="title">Title:</label>
      <input type="text" name="title" id="title" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="slug">Slug:</label>
      <input type="text" name="slug" id="slug" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="category">Category:</label>
      <select name="category" id="category" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
        <option value="">Select a category</option>
        {% for category in categories %}
          <option value="{{ category.id }}">{{ category.title}}</option>
        {% endfor %}
      </select>
    </div>



    <div class="seller-add-product-form">
      <label for="image">Image:</label>
      <input type="file" name="image" id="image" accept="image/*" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="marked_price">Marked Price:</label>
      <input type="number" name="marked_price" id="marked_price" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="selling_price">Selling Price:</label>
      <input type="number" name="selling_price" id="selling_price" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="description">Description:</label>
      <textarea name="description" id="description" rows="4" required style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;"></textarea>
    </div>


    <div class="seller-add-product-form">
      <label for="warranty">Warranty:</label>
      <input type="text" name="warranty" id="warranty" style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    <div class="seller-add-product-form">
      <label for="return_policy">Return Policy:</label>
      <input type="text" name="return_policy" id="return_policy" style="width: 100%;padding: 10px;border: 1px solid #ccc;margin-bottom: 10px;">
    </div>


    
    <div>
        <button type="submit" style="background-color:#04AA6D; color:#fff; 
        font-family:sans-serif; font-size:16px; font-weight:600; padding:10px 20px; border:none; cursor:pointer; border-radius:20px;">Add Product</button>
    </div>
    
</form>
  
</div>

{% endblock %}

Epicdeals/templates/sellerbase.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta name="csrf_token" content="{{ csrf_token }}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
        {%endblock%}

    </title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



</head>
<body id="body">
  

    <nav style="display: flex; justify-content: space-between; align-items: center; background-color: #1f2a33;
    padding: 10px; color: #fff; font-family: Arial, sans-serif; font-size: 25px;">
       <ul style="display: flex;">
           
           {% if request.user.is_authenticated %}
           <li style="list-style: none; margin-right: 15px;"><a href = "{% url 'seller:sellerhome' request.user.username %}">Home</a></li>
           <li style="list-style: none; margin-right: 15px;"><a href = "{% url 'seller:selleraddproduct' request.user.username %}">Add Product</a></li>
           <li style="list-style: none; margin-right: 15px;"><a href = "{% url 'seller:sellerprofile' request.user.username %}">Orders</a></li>
           {% else %}
           <li style="list-style: none; margin-right: 15px;"><a href = "">Add Product</a></li>
           <li style="list-style: none; margin-right: 15px;"><a href = "">Orders</a></li>
           {% endif %}
           </li>
           
       </ul>
       <ul style="display: flex;">
          
           {% if request.user.seller_store %}
           <li style="list-style: none; margin-left: 15px;"><a href="">{{request.user.seller_store}}</a></li> 
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'seller:sellerlogout'%}">Logout</a></li>
           {% else %}
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'seller:sellerregistration' %}">Register</a></li> 
           <li style="list-style: none; margin-left: 15px;"><a href="{% url 'seller:sellerlogin' %}">Login</a></li> 
           {% endif %}
           
       </ul>
   </nav>
          

   <script>
     

     
  var category = document.getElementById("category");
  var dropdownOptions = document.getElementById("dropdownOptions");
  category.addEventListener("click", function(event) {


    if (dropdownOptions.style.display === "none") {
      dropdownOptions.style.display = "block";
    } else {
      dropdownOptions.style.display = "none";
    }



  });

  
   
  </script>
    

       {% block body %}
       {%endblock%}
</body>
</html>

Epicdeals/templates/sellerhome.html
{% extends 'sellerbase.html' %}

{% block title %} Seller Home{% endblock %}
{% block body %}
<div class="container" style="margin-top: 40px;">
    <h3>All Products</h3>
     

      <div class = "row">

        {% for p in products %}
        <div style="border: 1px solid #ccc; padding: 10px; text-align: center;background-color: rgb(229, 240, 240);height:400px;width:300px;margin: 20px;">
          <a href="/product/{{p.slug}}"><img src="{{p.image.url}}" alt="Product Image" style="width: 100%;height: 250px;">
          <h3 style="margin-top: 10px;">{{p.title}}</h3></a>
          <p style="font-size: 18px;">TK.<strike> {{p.marked_price}}</strike> {{p.selling_price}}</p>
          <a href=""><button style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; font-size: 16px;">Views and Edit</button></a>
         </div>
      
         {% endfor %}


      </div>

  
  </div>

{% endblock %}

Epicdeals/templates/sellerlogin.html
{% extends 'sellerbase.html' %}

{% block title%}Seller login{%endblock%}
{% block body %}

<form method="POST",action ="{% url 'seller:sellerlogin' %}">
  <div class="login-form" style="margin:20px auto;width:30%;">
    {% csrf_token %}
    <h1 style="text-align:center; font-size:30px; font-weight:bold; font-family:sans-serif; font-weight:600; text-align:center; margin-bottom:30px;">Login</h1>
    <div>
      <label>Store Name</label>
    <input type="text" name="store_name" placeholder="Store Name" style="width:100%; padding:10px; border:3px solid #ccc; border-radius:20px; margin-bottom:10px;">
  </div>

  <div>
    <lebel>Password</lebel>
    <input type="password" name="password" placeholder="Password" style="width:100%; padding:10px; border:3px solid #ccc; border-radius:20px; margin-bottom:10px;">
  </div>
    <button type="submit" style="background-color:#04AA6D; color:#fff; font-family:sans-serif; font-size:16px; 
    font-weight:600; padding:10px 20px; border:none; cursor:pointer; border-radius:20px;">Login</button>
    <p>Don't have account?<a href="{% url 'seller:sellerregistration' %}" style="text-decoration:none; color:#04AA6D; 
    font-family:sans-serif; font-size:20px; font-weight:600;">  Register</a></p>
  </div>

</form>
<div style="height:20px;width:100%;text-align: center;">
  
  {% for msg in messages %}

     <p style="color:red">{{msg}}</p>

{% endfor %}

</div>


{% endblock %}

Epicdeals/templates/sellerprofile.html
{% extends 'sellerbase.html' %}

{% block title%}user profile{%endblock%}
{% block body %}



<div class="container">
    <div class="row">
        <div class="col-md mx-auto">
            <div>

            <h3>Seller Information</h3><hr>
            <p><span class="font-weight-bold">Seller_Store : </span> {{seller_info.store_name}}</p>
           
            <p><span class="font-weight-bold">Email : </span>{{seller_info.email}}</p>
            <p><span class="font-weight-bold">Address : </span>{{seller_info.address}}</p>
            <p><span class="font-weight-bold">Contact No :  </span>{{seller_info.contact_number}}</p>
            <hr>
            </div>
            <div style="margin-top: 40px;">
            <h3>Pending Order</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order_id</th>
                        <th>Amount</th>
                        <th>Ordered_on</th>
                        <th>Status</th>
                        <th>Ordered_By</th>
                        
                    </tr>
                    <tbody>
                        
                        {% for ord in pendingorders %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'seller:sellerorderdetail' seller_info.store_name ord.id  %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                        <td>{{ord.ordered_by}}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </thead>
            </table>
        </div>
        </div>
   
     
   
    
 
{% endblock %}

Epicdeals/templates/sellerregistration.html
{% extends 'sellerbase.html' %}

{% block title%}Seller login{%endblock%}
{% block body %}

<form  action="{% url 'seller:sellerregistration' %}" method="POST">
<div class="login-form" style="margin:20px auto;width:30%;">
    {% csrf_token %}
    <h1 style="text-align:center; font-size:30px; font-weight:bold; font-family:sans-serif; font-weight:600; text-align:center; margin-bottom:30px;">Seller Registration</h1>
    <div>
     <lebel>Store name</lebel>
    <input type="text" name="store_name" placeholder="Store Name" style="width:100%; padding:10px; border:1px solid #141212; border-radius:20px; margin-bottom:10px;">
    </div>

    <div>
      <lebel>Email</lebel>
    <input type="email" name="email" placeholder="Email" style="width:100%; padding:10px; border:1px solid #141212; border-radius:20px; margin-bottom:10px;">
    </div>

    <div>
     <label>Password</label>
    <input type="password" name="password" placeholder="Password" style="width:100%; padding:10px; border:1px solid #141212; border-radius:20px; margin-bottom:10px;">
    </div>

     <div>
      <label>Address</label>
    <input type="text" name = "address" placeholder="Address" style="width:100%; padding:10px; border:1px solid #141212; border-radius:20px; margin-bottom:10px;">
    </div>

    <div>
      <label>Contact no</label>
    <input type="text" name="contact_number" placeholder="Contact No" style="width:100%; padding:10px; border:1px solid #141212; border-radius:20px; margin-bottom:10px;">
    </div>
   


    
    <button type="submit" style="background-color:#04AA6D; color:#fff; font-family:sans-serif; font-size:16px; 
    font-weight:600; padding:10px 20px; border:none; cursor:pointer; border-radius:20px;">Register</button>
    <p>Already have account?<a href="{% url 'seller:sellerlogin' %}" style="text-decoration:none; color:#04AA6D;
     font-family:sans-serif; font-size:20px; font-weight:600;">  Login</a></p>
  </div>
</form>
<div style="height:20px;width:100%;text-align: center;">
  
    {% for msg in messages %}

       <p style="color:red">{{msg}}</p>
  
  {% endfor %}

  </div>




{% endblock %}